name: cicd

on: 
  push:
    branches: [ main ]

env:
  BUILD_CONFIGURATION: Production

jobs:
  

  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:

      - name: Job environment
        run: echo $BUILD_CONFIGURATION
      - name: Use secret
        run: |
          echo "Access Token: ${{ secrets.ACCESS_TOKEN }}"
      
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build --if-present
      - name: Run tests
        run: npm test


