name: cicd

on: 
  push:
    branches: [ main ]

env:
  BUILD_CONFIGURATION: Production

jobs:
  

  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:

      - name: Job environment
        run: echo $BUILD_CONFIGURATION
      - name: Use secret
        run: |
          echo "Access Token: ${{ secrets.ACCESS_TOKEN }}"

      - name: Conditional step
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        run: echo "This step runs only for pull requests."

      - name: Set Output
        id: data_generator
        run: echo "::set-output name=data_gen::$(echo data consumption)"

      - name: Use Output
        id: data_consumer
        run: |
          echo "Received value from previous step: ${{ steps.data_generator.outputs.data_gen }}"
      
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build --if-present
      - name: Run tests
        run: npm test


